//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImoBarcelosRest
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adminidtrador
    {
        public int IdAdminidtrador { get; set; }
        public string DataAdmissao { get; set; }
        public string DataInicioAd { get; set; }
        public string DataFim { get; set; }
        public int Pessoa_IdPessoa { get; set; }
        public int Utilizador_IdUtilizador { get; set; }
    
        public virtual Utilizador Utilizador { get; set; }
        public virtual Pessoa Pessoa { get; set; }
    }
}
