//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImoBarcelosRest
{
    using System;
    using System.Collections.Generic;
    
    public partial class Arrendatario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Arrendatario()
        {
            this.Habitacao = new HashSet<Habitacao>();
        }
    
        public int IdArrendatario { get; set; }
        public string DataInicio { get; set; }
        public Nullable<int> Pessoa_IdPessoa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Habitacao> Habitacao { get; set; }
        public virtual Pessoa Pessoa { get; set; }
    }
}
