//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImoBarcelosRest
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cliente()
        {
            this.RClienteHoobieSet = new HashSet<RClienteHoobieSet>();
            this.RClienteRInstituto = new HashSet<RClienteRInstituto>();
        }
    
        public int IdCliente { get; set; }
        public string Facebook { get; set; }
        public string Linkedlin { get; set; }
        public string Twiter { get; set; }
        public string Instituto { get; set; }
        public string Curso { get; set; }
        public string AnoEscolar { get; set; }
        public int Pessoa_IdPessoa { get; set; }
        public int Utilizador_IdUtilizador { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RClienteHoobieSet> RClienteHoobieSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RClienteRInstituto> RClienteRInstituto { get; set; }
        public virtual Pessoa Pessoa { get; set; }
        public virtual Utilizador Utilizador { get; set; }
    }
}
