//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImoBarcelosRest
{
    using System;
    using System.Collections.Generic;
    
    public partial class Funcionario
    {
        public int IdFuncionario { get; set; }
        public Nullable<int> NInterno { get; set; }
        public string DataAdmissao { get; set; }
        public Nullable<int> Pessoa_IdPessoa { get; set; }
        public Nullable<int> Utilizador_IdUtilizador { get; set; }
    
        public virtual Pessoa Pessoa { get; set; }
        public virtual Utilizador Utilizador { get; set; }
    }
}
