//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HumanControlServicos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Habitacao
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Habitacao()
        {
            this.RelacaoHabitacaRestricao = new HashSet<RelacaoHabitacaRestricao>();
            this.RHabitacaoPontos = new HashSet<RHabitacaoPontos>();
            this.Room = new HashSet<Room>();
            this.RHabitacaoImagem = new HashSet<RHabitacaoImagem>();
        }
    
        public int IdHabitacao { get; set; }
        public string Morada { get; set; }
        public string NAssoalhadas { get; set; }
        public string NQuartos { get; set; }
        public string Area { get; set; }
        public string AnoConstrucao { get; set; }
        public string Internet { get; set; }
        public string Wifi { get; set; }
        public string Tipologia { get; set; }
        public int Arrendatario_IdArrendatario { get; set; }
    
        public virtual Arrendatario Arrendatario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RelacaoHabitacaRestricao> RelacaoHabitacaRestricao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RHabitacaoPontos> RHabitacaoPontos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Room> Room { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RHabitacaoImagem> RHabitacaoImagem { get; set; }
    }
}
