//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HumanControlServicos
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoricoAluguer
    {
        public int IdHistoricoAluguer { get; set; }
        public string DataInicio { get; set; }
        public string DataFim { get; set; }
        public string DataReserva { get; set; }
        public int Utilizador_IdUtilizador { get; set; }
        public int Room_IdRoom { get; set; }
    
        public virtual Utilizador Utilizador { get; set; }
    }
}
