//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImoBarcelosRest
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBImobiliarioEntities : DbContext
    {
        public DBImobiliarioEntities()
            : base("name=DBImobiliarioEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Adminidtrador> Adminidtrador { get; set; }
        public virtual DbSet<Ano> Ano { get; set; }
        public virtual DbSet<Arrendatario> Arrendatario { get; set; }
        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<Curso> Curso { get; set; }
        public virtual DbSet<Funcionario> Funcionario { get; set; }
        public virtual DbSet<Genero> Genero { get; set; }
        public virtual DbSet<Habitacao> Habitacao { get; set; }
        public virtual DbSet<HistoricoAluguer> HistoricoAluguer { get; set; }
        public virtual DbSet<Hobbie> Hobbie { get; set; }
        public virtual DbSet<Imagem> Imagem { get; set; }
        public virtual DbSet<Instituto> Instituto { get; set; }
        public virtual DbSet<Pessoa> Pessoa { get; set; }
        public virtual DbSet<PontosInteresse> PontosInteresse { get; set; }
        public virtual DbSet<RClienteHoobieSet> RClienteHoobieSet { get; set; }
        public virtual DbSet<RClienteRInstituto> RClienteRInstituto { get; set; }
        public virtual DbSet<RelacaoHabitacaRestricao> RelacaoHabitacaRestricao { get; set; }
        public virtual DbSet<Restricaoo> Restricaoo { get; set; }
        public virtual DbSet<RHabitacaoImagem> RHabitacaoImagem { get; set; }
        public virtual DbSet<RHabitacaoPontos> RHabitacaoPontos { get; set; }
        public virtual DbSet<RInstitutoCursoAno> RInstitutoCursoAno { get; set; }
        public virtual DbSet<Utilizador> Utilizador { get; set; }
        public virtual DbSet<Room> Room { get; set; }
    }
}
