//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImoBarcelosRest
{
    using System;
    using System.Collections.Generic;
    
    public partial class RClienteHoobieSet
    {
        public int IdRelacao { get; set; }
        public int Cliente_IdCliente { get; set; }
        public int Hobbie_IdHobbie { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Hobbie Hobbie { get; set; }
    }
}
