//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImoBarcelosRest
{
    using System;
    using System.Collections.Generic;
    
    public partial class RHabitacaoImagem
    {
        public int IdRHabitacaoImagem { get; set; }
        public int IdRHabitacao { get; set; }
        public int IdRImagem { get; set; }
    
        public virtual Habitacao Habitacao { get; set; }
        public virtual Imagem Imagem { get; set; }
    }
}
