//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImoBarcelosRest
{
    using System;
    using System.Collections.Generic;
    
    public partial class RHabitacaoPontos
    {
        public int IdRHabitacaoPontos { get; set; }
        public string Data { get; set; }
        public int Habitacao_IdHabitacao { get; set; }
        public int PontosInteresse_IdPontosInteresse { get; set; }
    
        public virtual Habitacao Habitacao { get; set; }
        public virtual PontosInteresse PontosInteresse { get; set; }
    }
}
