//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HumanControlServicos
{
    using System;
    using System.Collections.Generic;
    
    public partial class RInstitutoCursoAno
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RInstitutoCursoAno()
        {
            this.RClienteRInstituto = new HashSet<RClienteRInstituto>();
        }
    
        public int IdRInstitutoCursoAno { get; set; }
        public string Data { get; set; }
        public int Instituto_IdInstituto { get; set; }
        public int Curso_IdCurso { get; set; }
        public int Ano_IdAno { get; set; }
    
        public virtual Ano Ano { get; set; }
        public virtual Curso Curso { get; set; }
        public virtual Instituto Instituto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RClienteRInstituto> RClienteRInstituto { get; set; }
    }
}
